---
sudo: false
language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
env:
  - SUB_PROJECT=WeatherClient;SUB_PROJECT_PATH=task5_16_11_2017/WeatherClient

install: true
script:
  - cd $SUB_PROJECT_PATH && mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash) -C -F $SUB_PROJECT

branches:
  only:
    - master
