---
sudo: false
language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
env:
  - PROJECT_FLAG=weather_client PROJECT_PATH=task5_16_11_2017/WeatherClient

install: true
script:
  - cd $PROJECT_PATH && mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF $PROJECT_FLAG

branches:
  only:
    - master
